apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: <1 - Name of AWS credentials>
  namespace: <2 - Namespace where the credentials will be saved>
  labels:
    cluster.open-cluster-management.io/type: aws
    cluster.open-cluster-management.io/credentials: ""
stringData:
  aws_access_key_id: <3 - AWS Access Key ID>
  aws_secret_access_key: <4 - AWS Secret Key>
  baseDomain: <5 - Base domain>
  pullSecret: >
    <6 Global pull secret>
  ssh-privatekey: |
    <7 - A SSH private key>
  ssh-publickey: >
    ssh-rsa
    <7 - A SSH public key>
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  additionalTrustBundle: ""
