kind: Service
apiVersion: v1
metadata:
  name: application-03
  namespace: application-03
  labels:
    app: application-03
    app.kubernetes.io/component: application-03
    app.kubernetes.io/instance: application-03
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: application-03
