apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-04
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: gitops-clusters-cpu
        requeueAfterSeconds: 180
  template:
    metadata:
      name: application-04-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/ignaciolago/multi-cluster-deploy.git
        targetRevision: main
        path: 04_deploy_applications/application-04
      destination:
        namespace: application-04
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
