---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: gitops-clusters-location
  namespace: openshift-gitops
spec:
  clusterSets:
    - gitops-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            area: fringe